from api_clients import call_openrouter
from models_registry import get_model
import json

async def synthesize_results(prompt: str, executed_tasks: list, session = None):
    """
    Returns the structured raw results, AND uses a Formatter Agent to write a cohesive summary.
    """
    formatter_model = get_model("orchestrator", 2) # Use the powerful model for formatting
    
    # Compile the raw results into a single string for the AI to read
    raw_text = ""
    for item in executed_tasks:
         raw_text += f"Agent {item['model']} completed task '{item['task']}' with result:\n{item['result']}\n\n"
         
    system_prompt = (
        "You are the Presentation Synthesizer Agent. "
        "Your job is to read the raw data generated by various domain experts, "
        "and rewrite it into a beautifully formatted, cohesive, and highly professional response for the user. "
        "Do not mention that you are formatting data; just present the final answer clearly."
    )
    
    formatter_prompt = f"User Request: {prompt}\n\nRaw Expert Data:\n{raw_text}\n\nPlease generate the final formatted response."
    
    print("Formatter Agent is synthesizing the final response...")
    formatted_summary = await call_openrouter(formatter_model, formatter_prompt, system_prompt, session=session)
    
    return {
        "orchestrator_model": None, # Will be injected by main.py
        "synthesizer_model": formatter_model,
        "summary": f"Executed {len(executed_tasks)} agents for request: '{prompt}'",
        "formatted_output": formatted_summary,
        "results": executed_tasks
    }
